/**
 * services/pageCount.service.js
 * Works out how many pages a file has, from its plaintext bytes, so
 * `document_versions.page_count` / `page_count_estimated` can be stored at
 * registration time. Dispatches by mimetype (falling back to the file
 * extension, since browsers/agents often label office files
 * application/octet-stream):
 *
 *   EXACT
 *   application/pdf                 -> pdf-lib page tree (pdf-parse as a fallback for odd files)
 *   image/tiff                      -> counts the TIFF IFD chain (multi-page scans)
 *   image/* (anything else)         -> 1
 *   .docx / .pptx                   -> the Pages / Slides figure the authoring app wrote to docProps/app.xml
 *                                      (pptx falls back to counting its slide parts)
 *   .xlsx / .xls / .ods             -> worksheet count (a spreadsheet has no fixed page layout)
 *   .odt / .odp                     -> meta:page-count from meta.xml
 *
 *   ESTIMATED (flagged, shown as "~N" in the UI — there is no fixed layout to count)
 *   text/* and .txt/.csv/.md/.log/.json/.xml -> laid out at 90 columns x 46 lines per page
 *   .docx with no Pages figure (generated by a library rather than Word) -> ~500 words per page
 *
 *   anything else (legacy .doc/.ppt, .rtf, unknown binaries) -> { count: null }, shown as "—"
 *
 * Like ocr.service.js this must never block registration: every counter is
 * wrapped so a failure logs a warning and resolves to { count: null }.
 */
const path = require('path');
const JSZip = require('jszip');
const XLSX = require('xlsx');
const mammoth = require('mammoth');
const { PDFDocument } = require('pdf-lib');
const { PDFParse } = require('pdf-parse');
const logger = require('../config/logger');

const MAX_TIFF_PAGES = 100000; // guards against a corrupt/looping IFD chain
const TEXT_COLUMNS = 90;
const TEXT_LINES_PER_PAGE = 46;
const WORDS_PER_PAGE = 500;
const TEXT_EXTENSIONS = new Set(['.txt', '.csv', '.md', '.log', '.json', '.xml']);

const exact = (count) => ({ count: count > 0 ? count : null, estimated: false });
const estimate = (count) => ({ count: count > 0 ? count : null, estimated: true });

async function countPdfPages(buffer) {
  try {
    const pdf = await PDFDocument.load(buffer, { ignoreEncryption: true, updateMetadata: false, throwOnInvalidObject: false });
    const n = pdf.getPageCount();
    if (n > 0) return exact(n);
  } catch {
    // fall through to pdf-parse below
  }
  const parser = new PDFParse({ data: buffer });
  try {
    const info = await parser.getInfo();
    return exact(info.total);
  } finally {
    await parser.destroy();
  }
}

function countTiffPages(buffer) {
  if (buffer.length < 8) return exact(0);
  const order = buffer.toString('latin1', 0, 2);
  if (order !== 'II' && order !== 'MM') return exact(0);
  const le = order === 'II';
  const u16 = (o) => (le ? buffer.readUInt16LE(o) : buffer.readUInt16BE(o));
  const u32 = (o) => (le ? buffer.readUInt32LE(o) : buffer.readUInt32BE(o));
  if (u16(2) !== 42) return exact(0); // BigTIFF (43) isn't handled

  let offset = u32(4);
  let pages = 0;
  const seen = new Set();
  while (offset > 0 && offset + 2 <= buffer.length && !seen.has(offset) && pages < MAX_TIFF_PAGES) {
    seen.add(offset);
    const entries = u16(offset);
    const nextPointer = offset + 2 + entries * 12;
    if (nextPointer + 4 > buffer.length) break;
    pages += 1;
    offset = u32(nextPointer);
  }
  return exact(pages);
}

function countTextPages(buffer) {
  const text = buffer.toString('utf8');
  if (!text.trim()) return exact(0);
  const lines = text.split(/\r\n|\r|\n/).reduce((sum, line) => sum + Math.max(1, Math.ceil(line.length / TEXT_COLUMNS)), 0);
  return estimate(Math.ceil(lines / TEXT_LINES_PER_PAGE));
}

async function readZipText(zip, entryName) {
  const entry = zip.file(entryName);
  return entry ? entry.async('string') : null;
}

async function countDocxPages(buffer) {
  const zip = await JSZip.loadAsync(buffer);
  const xml = await readZipText(zip, 'docProps/app.xml');
  const match = xml && /<Pages>(\d+)<\/Pages>/.exec(xml);
  if (match && Number(match[1]) > 0) return exact(Number(match[1]));

  const { value } = await mammoth.extractRawText({ buffer });
  const words = (value || '').split(/\s+/).filter(Boolean).length;
  return estimate(Math.ceil(words / WORDS_PER_PAGE));
}

async function countPptxSlides(buffer) {
  const zip = await JSZip.loadAsync(buffer);
  const xml = await readZipText(zip, 'docProps/app.xml');
  const match = xml && /<Slides>(\d+)<\/Slides>/.exec(xml);
  if (match && Number(match[1]) > 0) return exact(Number(match[1]));
  return exact(zip.file(/^ppt\/slides\/slide\d+\.xml$/).length);
}

async function countOdfPages(buffer, attribute) {
  const zip = await JSZip.loadAsync(buffer);
  const xml = await readZipText(zip, 'meta.xml');
  const match = xml && new RegExp(`${attribute}="(\\d+)"`).exec(xml);
  return exact(match ? Number(match[1]) : 0);
}

function countSheets(buffer) {
  const workbook = XLSX.read(buffer, { type: 'buffer', bookSheets: true });
  return exact(workbook.SheetNames.length);
}

/** The counter for this file type, or null when the type isn't one we can count. */
function pickCounter(mimetype, originalname) {
  const ext = path.extname(originalname || '').toLowerCase();
  const mime = mimetype || '';
  if (mime === 'application/pdf' || ext === '.pdf') return countPdfPages;
  if (mime === 'image/tiff' || ext === '.tif' || ext === '.tiff') return countTiffPages;
  if (mime.startsWith('image/')) return () => exact(1);
  if (ext === '.docx') return countDocxPages;
  if (ext === '.pptx') return countPptxSlides;
  if (ext === '.xlsx' || ext === '.xls') return countSheets;
  if (ext === '.odt' || ext === '.odp') return (b) => countOdfPages(b, 'meta:page-count');
  if (ext === '.ods') return (b) => countOdfPages(b, 'meta:table-count');
  if (mime.startsWith('text/') || TEXT_EXTENSIONS.has(ext)) return countTextPages;
  return null;
}

/** Whether countPages can ever return a number for this type — lets a backfill skip downloading the rest. */
function isCountable(mimetype, originalname) {
  return pickCounter(mimetype, originalname) !== null;
}

/**
 * @returns {Promise<{count: number|null, estimated: boolean}>} count is null when it can't be determined
 */
async function countPages(buffer, mimetype, originalname) {
  const counter = pickCounter(mimetype, originalname);
  if (!counter) return { count: null, estimated: false };
  try {
    return await counter(buffer);
  } catch (err) {
    logger.warn('Page count failed', { originalname, mimetype, error: err.message });
    return { count: null, estimated: false };
  }
}

module.exports = { countPages, isCountable };
